import Card from '@/components/Card/Card';
import Heading from '@/components/Heading/Heading';
import Link from 'next/link';

import Head from 'next/head';
import { supabase } from '../../lib/subabaseClient';

export default function Poets({ poets }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="root mt-1 mobile:py-1">
        <Heading
          variant="medium"
          title="Poet's Page"
          extraClasses="font-bold text-center mb-6"
        />
        <main className="grid grid-cols-3  justify-center items-center gap-y-6 gap-x-5 ">
          {poets &&
            poets.map((poet: any) => {
              return (
                <Link
                  key={poet.id}
                  href={`/poets/${poet.id}`}
                  className="flex justify-center items-center border-2 border-black-800 bg-white shadow-[8.0px_8.0px_8.0px_rgba(0,0,0,0.38)] rounded-2xl p-1 hover:scale-[110%] "
                >
                  <Card
                    variant="poet"
                    title={poet.name}
                    imageSrc="/poet2.svg"
                  />
                </Link>
              );
            })}
        </main>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  let { data } = await supabase.from('poets').select();
  return {
    props: {
      poets: data,
    },
  };
}
