import Head from "next/head";
import { supabase } from "../lib/subabaseClient";

export default function Home({ poets }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello Next</main>
      {poets &&
        poets.map((poet: any) => {
          return <h1 key={poet.id}>{poet.name}</h1>;
        })}
    </>
  );
}

export async function getServerSideProps() {
  let { data } = await supabase.from("poets").select();
  return {
    props: {
      poets: data,
    },
  };
}
