import Button from '@/components/Button/Button';
import Card from '@/components/Card/Card';
import Heading from '@/components/Heading/Heading';
import Input from '@/components/Input/Input';

import Text from '@/components/Text/Text';
import TextArea from '@/components/TextArea/TextArea';
import Head from 'next/head';
import { supabase } from '../lib/subabaseClient';

export default function Home({ poets }: any) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="root mt-16 mobile:py-4 mobile:mt-4">
        <Heading
          variant="x-large"
          title="Home Page"
          extraClasses="font-bold text-center mb-10"
        />
        <main className="grid grid-cols-3 mobile:grid-cols-1 gap-y-10 gap-x-6">
          Add data here
        </main>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  let { data } = await supabase.from('poets').select();
  return {
    props: {
      poets: data,
    },
  };
}
